using System.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Editing;
using Microsoft.CodeAnalysis.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace RoslynSamples.API.Syntax
{
    [TestClass]
    public class CodeGeneratingSamples
    {
        [TestMethod]
        public void EmptyCSharpClassGenerating()
        {
            //Compilation unit for representing single source file
            var compilationUnit = SyntaxFactory.CompilationUnit();


            var emptyClassSyntax = compilationUnit
                .WithMembers(
                    SyntaxFactory.SingletonList<MemberDeclarationSyntax>(
                        SyntaxFactory.ClassDeclaration("C")))
                .NormalizeWhitespace();
            
            Trace.WriteLine(emptyClassSyntax.ToFullString());
        }

        [TestMethod]
        public void TestClassGenerating()
        {

            //Generated by https://roslynquoter.azurewebsites.net/
            #region TestClassGenerate
            var testClass = SyntaxFactory.CompilationUnit()
                .WithMembers(
                    SyntaxFactory.SingletonList<MemberDeclarationSyntax>(
                        SyntaxFactory.ClassDeclaration("CodeGeneratingSamples")
                            .WithAttributeLists(
                                SyntaxFactory.SingletonList<AttributeListSyntax>(
                                    SyntaxFactory.AttributeList(
                                        SyntaxFactory.SingletonSeparatedList<AttributeSyntax>(
                                            SyntaxFactory.Attribute(
                                                SyntaxFactory.IdentifierName("TestClass"))))))
                            .WithModifiers(
                                SyntaxFactory.TokenList(
                                    SyntaxFactory.Token(SyntaxKind.PublicKeyword)))
                            .WithMembers(
                                SyntaxFactory.SingletonList<MemberDeclarationSyntax>(
                                    SyntaxFactory.MethodDeclaration(
                                            SyntaxFactory.PredefinedType(
                                                SyntaxFactory.Token(SyntaxKind.VoidKeyword)),
                                            SyntaxFactory.Identifier("EmptyCSharpClassGenerating"))
                                        .WithAttributeLists(
                                            SyntaxFactory.SingletonList<AttributeListSyntax>(
                                                SyntaxFactory.AttributeList(
                                                    SyntaxFactory.SingletonSeparatedList<AttributeSyntax>(
                                                        SyntaxFactory.Attribute(
                                                            SyntaxFactory.IdentifierName("TestMethod"))))))
                                        .WithModifiers(
                                            SyntaxFactory.TokenList(
                                                SyntaxFactory.Token(SyntaxKind.PublicKeyword)))
                                        .WithBody(
                                            SyntaxFactory.Block(
                                                SyntaxFactory.LocalDeclarationStatement(
                                                    SyntaxFactory.VariableDeclaration(
                                                            SyntaxFactory.IdentifierName(
                                                                SyntaxFactory.Identifier(
                                                                    SyntaxFactory.TriviaList(
                                                                        SyntaxFactory.Comment(
                                                                            "//Compilation unit for representing single source file")),
                                                                    "var",
                                                                    SyntaxFactory.TriviaList())))
                                                        .WithVariables(
                                                            SyntaxFactory
                                                                .SingletonSeparatedList<VariableDeclaratorSyntax>(
                                                                    SyntaxFactory.VariableDeclarator(
                                                                            SyntaxFactory.Identifier("compilationUnit"))
                                                                        .WithInitializer(
                                                                            SyntaxFactory.EqualsValueClause(
                                                                                SyntaxFactory.InvocationExpression(
                                                                                    SyntaxFactory
                                                                                        .MemberAccessExpression(
                                                                                            SyntaxKind
                                                                                                .SimpleMemberAccessExpression,
                                                                                            SyntaxFactory
                                                                                                .IdentifierName(
                                                                                                    "SyntaxFactory"),
                                                                                            SyntaxFactory
                                                                                                .IdentifierName(
                                                                                                    "CompilationUnit")))))))),
                                                SyntaxFactory.LocalDeclarationStatement(
                                                    SyntaxFactory.VariableDeclaration(
                                                            SyntaxFactory.IdentifierName("var"))
                                                        .WithVariables(
                                                            SyntaxFactory
                                                                .SingletonSeparatedList<VariableDeclaratorSyntax>(
                                                                    SyntaxFactory.VariableDeclarator(
                                                                            SyntaxFactory.Identifier(
                                                                                "emptyClassSyntax"))
                                                                        .WithInitializer(
                                                                            SyntaxFactory.EqualsValueClause(
                                                                                SyntaxFactory.InvocationExpression(
                                                                                    SyntaxFactory
                                                                                        .MemberAccessExpression(
                                                                                            SyntaxKind
                                                                                                .SimpleMemberAccessExpression,
                                                                                            SyntaxFactory
                                                                                                .InvocationExpression(
                                                                                                    SyntaxFactory
                                                                                                        .MemberAccessExpression(
                                                                                                            SyntaxKind
                                                                                                                .SimpleMemberAccessExpression,
                                                                                                            SyntaxFactory
                                                                                                                .IdentifierName(
                                                                                                                    "compilationUnit"),
                                                                                                            SyntaxFactory
                                                                                                                .IdentifierName(
                                                                                                                    "WithMembers")))
                                                                                                .WithArgumentList(
                                                                                                    SyntaxFactory
                                                                                                        .ArgumentList(
                                                                                                            SyntaxFactory
                                                                                                                .SingletonSeparatedList
                                                                                                                <ArgumentSyntax
                                                                                                                >(
                                                                                                                    SyntaxFactory
                                                                                                                        .Argument(
                                                                                                                            SyntaxFactory
                                                                                                                                .InvocationExpression(
                                                                                                                                    SyntaxFactory
                                                                                                                                        .MemberAccessExpression(
                                                                                                                                            SyntaxKind
                                                                                                                                                .SimpleMemberAccessExpression,
                                                                                                                                            SyntaxFactory
                                                                                                                                                .IdentifierName(
                                                                                                                                                    "SyntaxFactory"),
                                                                                                                                            SyntaxFactory
                                                                                                                                                .GenericName(
                                                                                                                                                    SyntaxFactory
                                                                                                                                                        .Identifier(
                                                                                                                                                            "SingletonList"))
                                                                                                                                                .WithTypeArgumentList(
                                                                                                                                                    SyntaxFactory
                                                                                                                                                        .TypeArgumentList(
                                                                                                                                                            SyntaxFactory
                                                                                                                                                                .SingletonSeparatedList
                                                                                                                                                                <TypeSyntax
                                                                                                                                                                >(
                                                                                                                                                                    SyntaxFactory
                                                                                                                                                                        .IdentifierName(
                                                                                                                                                                            "MemberDeclarationSyntax"))))))
                                                                                                                                .WithArgumentList(
                                                                                                                                    SyntaxFactory
                                                                                                                                        .ArgumentList(
                                                                                                                                            SyntaxFactory
                                                                                                                                                .SingletonSeparatedList
                                                                                                                                                <ArgumentSyntax
                                                                                                                                                >(
                                                                                                                                                    SyntaxFactory
                                                                                                                                                        .Argument(
                                                                                                                                                            SyntaxFactory
                                                                                                                                                                .InvocationExpression(
                                                                                                                                                                    SyntaxFactory
                                                                                                                                                                        .MemberAccessExpression(
                                                                                                                                                                            SyntaxKind
                                                                                                                                                                                .SimpleMemberAccessExpression,
                                                                                                                                                                            SyntaxFactory
                                                                                                                                                                                .IdentifierName(
                                                                                                                                                                                    "SyntaxFactory"),
                                                                                                                                                                            SyntaxFactory
                                                                                                                                                                                .IdentifierName(
                                                                                                                                                                                    "ClassDeclaration")))
                                                                                                                                                                .WithArgumentList(
                                                                                                                                                                    SyntaxFactory
                                                                                                                                                                        .ArgumentList(
                                                                                                                                                                            SyntaxFactory
                                                                                                                                                                                .SingletonSeparatedList
                                                                                                                                                                                <ArgumentSyntax
                                                                                                                                                                                >(
                                                                                                                                                                                    SyntaxFactory
                                                                                                                                                                                        .Argument(
                                                                                                                                                                                            SyntaxFactory
                                                                                                                                                                                                .LiteralExpression(
                                                                                                                                                                                                    SyntaxKind
                                                                                                                                                                                                        .StringLiteralExpression,
                                                                                                                                                                                                    SyntaxFactory
                                                                                                                                                                                                        .Literal(
                                                                                                                                                                                                            "C")))))))))))))),
                                                                                            SyntaxFactory
                                                                                                .IdentifierName(
                                                                                                    "NormalizeWhitespace")))))))),
                                                SyntaxFactory.ExpressionStatement(
                                                    SyntaxFactory.InvocationExpression(
                                                            SyntaxFactory.MemberAccessExpression(
                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                SyntaxFactory.IdentifierName("Trace"),
                                                                SyntaxFactory.IdentifierName("WriteLine")))
                                                        .WithArgumentList(
                                                            SyntaxFactory.ArgumentList(
                                                                SyntaxFactory.SingletonSeparatedList<ArgumentSyntax>(
                                                                    SyntaxFactory.Argument(
                                                                        SyntaxFactory.InvocationExpression(
                                                                            SyntaxFactory.MemberAccessExpression(
                                                                                SyntaxKind.SimpleMemberAccessExpression,
                                                                                SyntaxFactory.IdentifierName(
                                                                                    "emptyClassSyntax"),
                                                                                SyntaxFactory.IdentifierName(
                                                                                    "ToFullString"))))))))))))))
                .NormalizeWhitespace();
            #endregion
            
            Trace.WriteLine(testClass.ToFullString());
        }

        [TestMethod]
        public void WorkspaceSpecificGenerating()
        {
            //Create a Workspace object, that represents current state of editor, solutions and projects
            var workspace = new AdhocWorkspace();
            
            //Add new project to the workspace
            string projName = "NewProject";
            var projectId = ProjectId.CreateNewId();
            var versionStamp = VersionStamp.Create();
            var projectInfo = ProjectInfo.Create(projectId, versionStamp, projName, projName, LanguageNames.CSharp);
            var newProject = workspace.AddProject(projectInfo);

            //Create a generator specifically for this project
            var generator = SyntaxGenerator.GetGenerator(newProject);

            var classDeclaration = generator.ClassDeclaration("TestClass");
            classDeclaration = classDeclaration.NormalizeWhitespace();

            Trace.WriteLine(classDeclaration.ToFullString());
        }
    }
}
